apiVersion: v1
kind: Pod
spec:
  containers:
  - name: cdt
    image: quay.io/kummallinen/cdt-infra-eclipse-full:v0.3-ubuntu-16.04@sha256:e1670227a6a56c6be3c4062eb65983d567e435db61ed9e2ddcd599befb402bf9
    tty: true
    command: ["/bin/sh"]
    args: ["-c", "/home/cdt/.vnc/xstartup.sh && cat"]
    resources:
      requests:
        memory: "4Gi"
        cpu: "1.3"
      limits:
        memory: "4Gi"
        cpu: "1.3"
    volumeMounts:
    - name: settings-xml
      mountPath: /home/jenkins/.m2/settings.xml
      subPath: settings.xml
      readOnly: true
    - name: m2-repo
      mountPath: /home/jenkins/.m2/repository
    - name: volume-known-hosts
      mountPath: /home/jenkins/.ssh
  volumes:
  - name: settings-xml
    configMap: 
      name: m2-dir
      items:
      - key: settings.xml
        path: settings.xml
  - name: m2-repo
    emptyDir: {}
  - name: volume-known-hosts
    configMap:
      name: known-hosts